# Pull base image.
FROM node:0.10.38

MAINTAINER Guillaume Astier

# Set working directory.
WORKDIR /opt

# Install components
RUN apt-get update -qq && apt-get install -y build-essential
RUN apt-get install -y ruby ruby-dev

# Install framework
RUN gem install sass
RUN gem install compass

RUN npm install -g gulp grunt bower

VOLUME ["/opt"]
CMD ["npm", "start"]
